// ITEMS
export const GET_ITEMS_LIST_SUCCESS = 'GET_ITEMS_LIST_SUCCESS';
export const GET_ITEMS_LIST_FAIL = 'GET_ITEMS_LIST_FAIL';

export const GET_ITEMS_LIST_CATEGORY_SUCCESS = 'GET_ITEMS_LIST_CATEGORY_SUCCESS';
export const GET_ITEMS_LIST_CATEGORY_FAIL = 'GET_ITEMS_LIST_CATEGORY_FAIL';

export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAIL = 'GET_ITEM_FAIL';

export const GET_SEARCH_ITEM_SUCCESS = 'GET_SEARCH_ITEM_SUCCESS';
export const GET_SEARCH_ITEM_FAIL = 'GET_SEARCH_ITEM_FAIL';

// PRODUCTS
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_LIST_SUCCESS';
export const GET_PRODUCTS_LIST_FAIL = 'GET_PRODUCTS_LIST_FAIL';

export const GET_PRODUCTS_LIST_CATEGORY_SUCCESS = 'GET_PRODUCTS_LIST_CATEGORY_SUCCESS';
export const GET_PRODUCTS_LIST_CATEGORY_FAIL = 'GET_PRODUCTS_LIST_CATEGORY_FAIL';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

// CATEGORIES
export const GET_ITEM_CATEGORIES_SUCCESS = 'GET_ITEM_CATEGORIES_SUCCESS';
export const GET_ITEM_CATEGORIES_FAIL = 'GET_ITEM_CATEGORIES_FAIL';

export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_FAIL = 'GET_PRODUCT_CATEGORIES_FAIL';
