# Generated by Django 4.2.1 on 2023-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
