# Generated by Django 4.2.1 on 2023-06-30 23:08

import apps.inventory.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to=apps.inventory.models.item_directory_path)),
                ('units', models.PositiveIntegerField()),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_new', models.BooleanField(default=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProduct',
            fields=[
                ('item_product_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to=apps.inventory.models.product_directory_path)),
                ('units', models.PositiveIntegerField()),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.productcategory')),
                ('sub_items', models.ManyToManyField(blank=True, through='inventory.ItemProduct', to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
